### ISSUE TITLE
video frame not blocking

### ISSUE THREAD

**Issue by Cold-Wind1** [yokoffing/filterlists#107]
### Prerequisites

- [X] I am not using any other content blockers alongside uBO (Privacy Badger, AdGuard, Ghostery, Adblock Plus, etc.)
- [X] I verified that this is not a [known filter issue](https://github.com/yokoffing/filterlists/issues)
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the uBO issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBO in the browser

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Specific URL(s) where the issue occurs

```bash
https://atlasos.net/
```

### Description

I am using yokoffing's click2load filters on ubo but video frame is not blocking.

### Steps to Reproduce

just add yokoffing's click2load filters to ubo and open the site

### Logger Output

```shell
.
```

### Expected behavior

click to load

### Actual behavior

video frames showing instead of click to load

### uBlock Origin version

1.52.2

### Browser name and version

Brave Browser

### Operating System and version

Windows 10

**Comment by yokoffing** [comment]
Not possible with `$3p,frame,redirect=click2load.html`. The "video frame" is an image.

Atlasos uses YouTube for the video player. YouTube only loads after clicking the two placeholders, and `click2load` already kicks in on the third screen where there's a `youtube-nocookie.com/` embed.
