### ISSUE TITLE
Link to the filter list is unavailable and cant access.

### ISSUE THREAD

**Issue by Domsicols** [yokoffing/filterlists#108]
![image](https://github.com/yokoffing/filterlists/assets/104392824/5cde6865-805a-48e4-bd5d-a2c068ebbb3c)

**Comment by yokoffing** [comment]
The "add" links were replaced recently with "subscribe" links. The subscribe links will activate only for uBlock Origin (i.e., they won't open on Safari).

To view a list, just click the hyperlinks to the left of subscribe.

![filters issues link](https://github.com/yokoffing/filterlists/assets/11689349/660a38a9-5d80-49b2-8342-d285b0a3bd56)
