### ISSUE TITLE
Certain replies to tweets containing videos blocked when clicked

### ISSUE THREAD

**Issue by Lordiun** [yokoffing/filterlists#122]
### Prerequisites

- [X] I am not using any other content blockers alongside uBO (Privacy Badger, AdGuard, Ghostery, Adblock Plus, etc.)
- [X] I verified that this is not a [known filter issue](https://github.com/yokoffing/filterlists/issues)
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the uBO issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBO in the browser

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Specific URL(s) where the issue occurs

```bash
https://twitter.com/Alrz612/status/1728527621867130937

https://twitter.com/smooyacs/status/1728364037958987979
```

### Description

From what i can tell, while using yokoffing's annoyance list when you click on a reply on a tweet specifically containing a video you have a chance of the reply you clicked on being blocked and it ends up being very confusing where you're actually replying. I believe i have narrowed it down to the rule below creating the issue for me as creating an exception seems to fix it. But why this seems to happen to some comments and not others i cannot figure out.

! [User] follows
!twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion##article div>svg>g>[d^="M17.863 13.44c1.477"]:upward(article)

### Steps to Reproduce

1. Go to the main tweets of the replies that i have linked
2. click on either reply that i have linked to

### Logger Output

```shell
<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +19 | \|\|twitter.com/i/api/1.1/jot | -- | twitter.com | 1 | post | xhr | `https://twitter.com/i/api/1.1/jot/client_event.json` |
| +17 | \|\|twitter.com/i/api/1.1/jot | -- | twitter.com | 1 | post | xhr | `https://twitter.com/i/api/1.1/jot/client_event.json` |
| +14 | \|\|twitter.com/i/api/1.1/jot | -- | twitter.com | 1 | post | xhr | `https://twitter.com/i/api/1.1/jot/client_event.json` |
| +10 | \|\|twitter.com/i/api/1.1/jot | -- | twitter.com | 1 | post | xhr | `https://twitter.com/i/api/1.1/jot/client_event.json` |
| +7 | \|\|twitter.com/i/api/1.1/jot | -- | twitter.com | 1 | post | xhr | `https://twitter.com/i/api/1.1/jot/client_event.json` |
| +7 | ##article div>svg>g>[d^="M17.863 13.44c1.477"]:upward(article) |  | twitter.com |  | get | dom | `https://twitter.com/Alrz612/status/1728527621867130937` |
| +7 | ##[aria-label$="trending now" i] |  | twitter.com |  | get | dom | `https://twitter.com/Alrz612/status/1728527621867130937` |
| +6 | \|\|twitter.com/i/api/1.1/jot | -- | twitter.com | 1 | post | xhr | `https://twitter.com/i/api/1.1/jot/client_event.json` |
| +6 | ##[aria-label="relevant people" i]:upward(1) |  | twitter.com |  | get | dom | `https://twitter.com/Alrz612/status/1728527621867130937` |
| +3 | \|\|twitter.com/i/api/1.1/jot | -- | twitter.com | 1 | post | xhr | `https://twitter.com/i/api/1.1/jot/client_event.json` |
| +3 | \|\|twitter.com/i/api/1.1/jot | -- | twitter.com | 1 | post | xhr | `https://twitter.com/i/api/1.1/jot/client_event.json` |
| +3 | ##html:style(overflow:auto!important) |  | twitter.com |  | get | dom | `https://twitter.com/Alrz612/status/1728527621867130937` |
| +2 | ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyLHRleHRfdmVyc2lvbjoxMDAw) |  | twitter.com |  | get | scriptlet | `https://twitter.com/Alrz612/status/1728527621867130937` |
| +2 | \|\|ads-twitter.com^ | -- | twitter.com | 3 | get | script | `https://static.ads-twitter.com/uwt.js` |
| +0 | \|\|twitter.com/i/api/1.1/jot | -- | twitter.com | 1 | post | xhr | `https://twitter.com/i/api/1.1/jot/client_event.json` |
</details>
```

### Expected behavior

Being able to see the reply you have pressed on as the tweet "in focus"

### Actual behavior

the reply you click gets hidden and you can no longer read it

### uBlock Origin version

1.53.0

### Browser name and version

Firefox 120.0

**Comment by yokoffing** [comment]
If I understand you correctly, then I am not able to reproduce. But I may not understand the issue 100% 🙃 

Can you send:

1. A screenshot of the way they should look
2. A screenshot of what the breakage is.

Thanks

**Comment by Lordiun** [comment]
Absolutely mate, I'm sure my wording wasn't the best as well, apologies. Hopefully this demonstrates it (note the twitter url and the "replying to" showing that I've clicked on the replies to try reply to them and not the main post)
https://imgur.com/a/2mq4xP9

**Comment by yokoffing** [comment]
Thank you for reporting! I've commented out the rule
```
! [User] follows
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion##article div>svg>g>[d^="M17.863 13.44c1.477"]:upward(article)
```
until I find a replacement.

**Comment by sinazadeh** [comment]
Unfortunately, I experienced a similar issue with uBlock Origin. Whenever I click on a tweet, I can only see the replies and not the original tweet. Here's a temporary fix that worked for me:
```
no-cosmetic-filtering: x.com true
no-cosmetic-filtering: twitter.com true
```

**Comment by yokoffing** [comment]
https://github.com/yokoffing/filterlists/issues/151#issuecomment-2233883897
