### ISSUE TITLE
Privacy Extended

### ISSUE THREAD

**Issue by s7xxrs** [yokoffing/filterlists#124]
I can't find the Privacy Extended list

I am trying to use the Pro Setup but it is not in the README.

Is it outdated or is it no longer needed?

In case it is no longer needed do u have another good list that covers AdGuard Tracking Protection?

Thank you!

**Comment by yokoffing** [comment]
Apologies. I removed the list elsewhere, but forgot to remove it from that section. Privacy Extended hasn’t been updated in a few months. I’ll add it back if the dev starts back with regular updates.

You should be more than okay with the other lists. You can just use AdGuard Tracking Protection, if you really want it.

**Comment by s7xxrs** [comment]
All good, the lists works amazing i have found the Privacy Extended list should i still use it or what do you recommend me?

Privacy lists are a must have for me, that's why I care so much, sorry for the inconvenience.

**Comment by yokoffing** [comment]
AdGuard Tracking Protection is a good alternative since Privacy Extended has not received updates for two months. Besides, that's what it's based on,.
