### ISSUE TITLE
Allowlist union.fit

### ISSUE THREAD

**Issue by adworacz** [yokoffing/filterlists#127]
### Prerequisites

- [X] I am not using any other content blockers alongside uBO (Privacy Badger, AdGuard, Ghostery, Adblock Plus, etc.)
- [X] I verified that this is not a [known filter issue](https://github.com/yokoffing/filterlists/issues)
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the uBO issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBO in the browser

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Specific URL(s) where the issue occurs

```bash
www.union.fit
```

### Description

Union.fit is an event management platform for yoga studios.

The offending line is here: https://github.com/yokoffing/filterlists/blob/main/enhanced_site_protection.txt#L23

### Logger Output

```shell
N/A
```

### Expected behavior

union.fit to load

### Actual behavior

union.fit is blocked

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/1991

**Comment by yokoffing** [comment]
https://github.com/yokoffing/filterlists/commit/7244eceb030d4a3156ef03577f4a319ef0bf1986
