### ISSUE TITLE
Website loading problem

### ISSUE THREAD

**Issue by ghost** [yokoffing/filterlists#129]
### Prerequisites

- [X] I am not using any other content blockers alongside uBO (Privacy Badger, AdGuard, Ghostery, Adblock Plus, etc.)
- [X] I verified that this is not a [known filter issue](https://github.com/yokoffing/filterlists/issues)
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the uBO issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBO in the browser

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Specific URL(s) where the issue occurs

```bash
.
```

### Description

website not loading properly

### Steps to Reproduce

Go to Brave Shields then add this url of https://github.com/yokoffing/filterlists/raw/main/block_third_party_fonts.txt to ' Enter filter list url ' and open the website.

### Logger Output

```shell
.
```

### Expected behavior

.

### Actual behavior

.

### uBlock Origin version

.

### Browser name and version

.

### Operating System and version

.

**Comment by yokoffing** [comment]
I can load the site on Firefox w/ uBO with that filter and on Chrome with uBO Lite. Perhaps Brave has a weird rule somewhere, or you're using other custom filters.

This repo officially supports uBO, not Brave Shields.

**Comment by yokoffing** [comment]
I downloaded Brave, added the list, and the site loads fine.
