### ISSUE TITLE
Removes Subscribe button

### ISSUE THREAD

**Issue by Linnshet** [yokoffing/filterlists#130]
### Prerequisites

- [X] I am not using any other content blockers alongside uBO (Privacy Badger, AdGuard, Ghostery, Adblock Plus, etc.)
- [X] I verified that this is not a [known filter issue](https://github.com/yokoffing/filterlists/issues)
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the uBO issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBO in the browser

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Specific URL(s) where the issue occurs

```bash
youtube.com
```

### Description

I disabled the Clear YouTube filter list specifically to test it, and the subscribe button disappears.

### Logger Output

```shell
-
```

### Expected behavior

-

### Actual behavior

-

**Comment by Linnshet** [comment]
Ohhhh, I thought this was a repository specifically for the YouTube Clear View filter list, that's what I clicked on. Now it makes more sense, my apologies.

But, still pretty self-explanatory I hope.

**Comment by yokoffing** [comment]
Please post two screenshots. One of what you expect to happen, and one of what actually happens. I still have a subscribe button when using the list.

**Comment by Linnshet** [comment]
![image](https://github.com/yokoffing/filterlists/assets/52015410/c18ac4f5-76c0-4543-a7c0-17bcc17764c3)

**Comment by yokoffing** [comment]
Thanks for reporting! I could not reproduce last night, but I can now.

**Comment by yokoffing** [comment]
No longer applicable
