### ISSUE TITLE
Scrollbar disappearing

### ISSUE THREAD

**Issue by Broken-Glass1** [yokoffing/filterlists#133]
### Prerequisites

- [X] I am not using any other content blockers alongside uBO (Privacy Badger, AdGuard, Ghostery, Adblock Plus, etc.)
- [X] I verified that this is not a [known filter issue](https://github.com/yokoffing/filterlists/issues)
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the uBO issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBO in the browser

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Specific URL(s) where the issue occurs

```bash
.
```

### Description

**_[Browse websites without logging in]_** filter causes disappearing of scrollbar on insta 

### Steps to Reproduce

.

### Logger Output

```shell
.
```

### Expected behavior

.

### Actual behavior

.

### uBlock Origin version

latest version 

### Browser name and version

brave

**Comment by yokoffing** [comment]
It’s not my filter. I list it in this repo as an option. Please report to https://github.com/DandelionSprout/adfilt/issues/new?assignees=&labels=Problem+report&projects=&template=problem-report-form.yml
