### ISSUE TITLE
Hagezi's Personal DNS Blocklist doesn't exist anymore?

### ISSUE THREAD

**Issue by brzzdev** [yokoffing/filterlists#135]
My `Hagezi's Personal DNS Blocklist` list was no longer updating inside uBlock, so I took a look at [their repo](https://github.com/hagezi/dns-blocklists/), and I can't find the list referenced anymore.

According to the [FAQ entry](https://github.com/hagezi/dns-blocklists/wiki/FAQ#whatshouldiuse) ` Which version of the lists should I use?`, the personal recommendation is now the `Pro` list. This appears much larger than the personal list was, but does import into uBlock without issues.

Assuming I'm not missing something, I think the recommendation needs to be updated, and I'd be curious to know what you'd recommend now.

**Comment by hagezi** [comment]
Light is the new Personal. See updated readme: https://github.com/yokoffing/filterlists#privacy

**Comment by brzzdev** [comment]
Ah, perfect. Thank you.

You still mention `Hagezi's Personal DNS Blocklist` in the `Custom Lists` section of `Pro`

**Comment by yokoffing** [comment]
@brzzdev Apologies. I thought I changed all the references in https://github.com/yokoffing/filterlists/commit/3ac3f3c4fb76ac47ee3f80f8d591621f4d52ce7a, but I missed one. Thanks for making me aware. I've fixed it now.
