### ISSUE TITLE
Bypass paywalls clean dead 

### ISSUE THREAD

**Issue by VVispy** [yokoffing/filterlists#139]
the magnolia filter list is dead https://twitter.com/Magnolia1234B/status/1779050596181438791

replace with the fork https://github.com/bpc-clone/bypass-paywalls-clean-filters
https://twitter.com/Magnolia1234B/status/1779818610426327329?t=MXUpchc1SyYUGa-_bXtdBg&s=19

**Comment by looser71** [comment]
https://github.com/bpc-clone/bypass-paywalls-clean-filters

**Comment by looser71** [comment]
https://twitter.com/Magnolia1234B/status/1779818610426327329?t=MXUpchc1SyYUGa-_bXtdBg&s=19

**Comment by yokoffing** [comment]
Thank you for the reminder!
