### ISSUE TITLE
[Question] Mobile AdBlocking

### ISSUE THREAD

**Issue by zkisaboss** [yokoffing/filterlists#140]
When you say "the link to the iOS versions is included for reference, but you don't need them when running AdGuard for iOS." does this mean you don't need to use the iOS link or you don't need to use any of the optimized filters?

**Comment by yokoffing** [comment]
You don't need to use the iOS links in AdGuard for iOS. AdGuard automatically uses the optimized filters in their iOS app, even though they don't explicitly label them as "optimized".

The guide includes a link to the iOS optimized filters mostly for reference.
