### ISSUE TITLE
TV9 Bangla Live TV: add click2load filter `static.vidgyor.com/player` 

### ISSUE THREAD

**Issue by pidus** [yokoffing/filterlists#142]
Site: https://tv9bangla.com/

Before:
![Screenshot_2024-04-28-14-32-47-355_com kiwibrowser browser](https://github.com/yokoffing/filterlists/assets/11857051/949fa848-711d-4981-a03f-a4aea8533ce9)

Filter used: `||static.vidgyor.com/player/$3p,frame,redirect=click2load.html`

After: 
![Screenshot_2024-04-28-14-33-11-028_com kiwibrowser browser](https://github.com/yokoffing/filterlists/assets/11857051/277d0ae9-92b7-497b-982e-079960b00d8e)

**Comment by yokoffing** [comment]
Added. Thanks!
