### ISSUE TITLE
Block service-rundfunkbeitrag.de scam site

### ISSUE THREAD

**Issue by ColinTimBarndt** [yokoffing/filterlists#147]
This site pretends to be an official site to change your details with the German broadcasting service, but they will ask for 30€ for any changes done. The official site is rundfunkbeitrag.de.

It would be cool if you could block this in [enhanced_site_protection.txt](https://github.com/yokoffing/filterlists/blob/main/enhanced_site_protection.txt).

**Comment by hagezi** [comment]
Ping @jarelllama

**Comment by iam-py-test** [comment]
Added to my blocklist.
Thanks

**Comment by ColinTimBarndt** [comment]
@yokoffing you blocked the official site instead of the scam

**Comment by yokoffing** [comment]
Fixed. Thanks
