### ISSUE TITLE
Brave Browser Addblock list recommendation and how to do it?

### ISSUE THREAD

**Issue by iHarryPotter178** [yokoffing/filterlists#148]
I know these works on ublock and Firefox, but i use brave browser and like it as well. is it possible to give some suggestions for this. I'm looking for the enhanced edition. I can't seem to add filter-list to brave list. subscribe button doesn't work. copying link doesn't work. It would be really great to have these. 
Thanks for your hard work.

**Comment by yokoffing** [comment]
For now, see https://github.com/yokoffing/filterlists?tab=readme-ov-file#other-ad-blockers.

Then,
1. Go to `brave://adblock` (or `brave://settings/shields/filters`; I'm away from my personal machine and can't recall exactly at the moment).
2. Put it in under the custom filter area. Add your own custom filter lists from different sources just copying/pasting the RAW URL and pressing save changes.

Later on, I can add specific instructions just for Brave.

**Comment by iHarryPotter178** [comment]
> For now, see https://github.com/yokoffing/filterlists?tab=readme-ov-file#other-ad-blockers.
> 
> Then,
> 
> 1. Go to `brave://adblock` (or `brave://settings/shields/filters`; I'm away from my personal machine and can't recall exactly at the moment).
> 2. Put it in under the custom filter area. Add your own custom filter lists from different sources just copying/pasting the RAW URL and pressing save changes.
> 
> Later on, I can add specific instructions just for Brave.

It seems like I skipped the other add blocker section when reading. I added some filters.. It would be great to get some suggestions, I'm using Nextdns premium as well, after getting the recommended here..

**Comment by yokoffing** [comment]
That's awesome!

Brave mainly uses the default uBlock filters. To add more filterlists, follow one of these examples: https://github.com/yokoffing/filterlists?tab=readme-ov-file#setup-examples

**Comment by yokoffing** [comment]
For instance, you could have something like this:

![brave example](https://github.com/yokoffing/filterlists/assets/11689349/49ecc9ff-0eb8-4b7f-a589-3c1f85508543)

**Comment by iHarryPotter178** [comment]
Thanks.. I'll definitely use this.. Should I close this?

**Comment by iHarryPotter178** [comment]
![Screenshot from 2024-06-30 14-47-10](https://github.com/yokoffing/filterlists/assets/78410114/cbac2f15-f583-4c97-a238-50863fa77a72)
I have set it up like this. thanks for the help. I'm closing it now. You can specifically mention brave browser in your guides, that would be helpful for other people.
