### ISSUE TITLE
Question about Cookie Lists for UBO

### ISSUE THREAD

**Issue by Dynamic5912** [yokoffing/filterlists#152]
Under UBO now there are 2 sets of Cookie Lists - EasyList and AdGuard. 

Your recommendation is to enable the EasyList ones - is there any benefit/differences between these and the AdGuard ones?

**Comment by yokoffing** [comment]
Two different groups of people maintain them. You can test and see if AdGuard provides more coverage the Easylist, but I think using both is redundant IMO.
