### ISSUE TITLE
Issue with click2load on Watch2Gether

### ISSUE THREAD

**Issue by Gaming12846** [yokoffing/filterlists#154]
### Prerequisites

- [X] I am not using any other content blockers alongside uBO (Privacy Badger, AdGuard, Ghostery, Adblock Plus, etc.)
- [X] I verified that this is not a [known filter issue](https://github.com/yokoffing/filterlists/issues)
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the uBO issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBO in the browser

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Specific URL(s) where the issue occurs

```bash
https://w2g.tv/
```

### Description

The videos on this website cannot be loaded by clicking on them. 

Occurs when the "click2load" custom filter or privacy essentials is enabled.

### Logger Output

```shell
19:51:47	||youtube.com^$frame,3p,from=~bing.com|~chatreplay.stream|~duckduckgo.com|~google.com|~video.search.yahoo.com	--	player.w2g.tv	3	get	frame	https://www.youtube.com/embed/?controls=0&disablekb=1&cc_load_policy=1&iv_load_policy=3&modestbranding=1&playsinline=1&enablecastapi=0&rel=0&showinfo=0&widget_referrer=https%3A%2F%2Fw2g.tv%2F&enablejsapi=1&origin=https%3A%2F%2Fplayer.w2g.tv&widgetid=1
```

### Expected behavior

Click to load the video, or disable click2load on this website, because this website only works when videos from other websites are embedded.

### Actual behavior

The video is blocked and nothing happens when I click on "click to load".

**Comment by yokoffing** [comment]
Thanks, I added the exception.
