### ISSUE TITLE
Clarification on the Pro Setup Example

### ISSUE THREAD

**Issue by MaidThatPrograms** [yokoffing/filterlists#156]
Based on what is written in the Pro setup example, the recommended setup is:
![{E661B116-60FC-4BAB-BAAD-501471B0C897}](https://github.com/user-attachments/assets/dc00a7ce-159b-4a32-8720-72cca76c446a)

Is this correct, or should any of the Custom Lists in the Enhanced setup example be included? I understand **yokoffing's click2load filters** would not be necessary since **Privacy Essentials** includes that. As far as I can tell, **Actually Legitimate URL Shortener Tool** is not included in any of the lists from the Pro setup. And since the Enhanced setup seems to suggest every filter list from the Security section, does **Most Abused TLDs** already include **Dandelion Sprout's Anti-Malware List** which it sounds like it might? Should I have **The malicious website blocklist** enabled?

**Comment by yokoffing** [comment]
Wow that was hard to read. I had to reword and space out your questions lol.

> 1. Should any of the Custom Lists from the Enhanced setup be included, or is the setup correct as is?

They should be included, except for `click2load` if you're using `Privacy Essentials`.

> 2. I understand that yokoffing's click2load filters are not necessary since Privacy Essentials includes that functionality. Is this correct?

Correct, on uBO.

> 3. It seems that the "Actually Legitimate URL Shortener Tool" is not included in any of the lists from the Pro setup. Should this list be added?

Yes. See question 1.

> 4. The Enhanced setup suggests including every filter list from the Security section.

Not every list, but it can be. It's up to your discretion.

> 5. Does the "Most Abused TLDs" list already include "Dandelion Sprout's Anti-Malware List"? It sounds like it might.

You can look by clicking the [links](https://github.com/yokoffing/filterlists?tab=readme-ov-file#security). But no, `Most Abused TLDs` includes a few TLDs sourced from the `Dandelion` list. This is noted under the description for `Most Abused TLDs`.

> 6. Should I have "The malicious website blocklist" enabled?

Maybe. See question 4.

**Comment by MaidThatPrograms** [comment]
Thank you for the clarification and sorry for writing it in a hard to read way!
