### ISSUE TITLE
Read more on geeksforgeeks.org 

### ISSUE THREAD

**Issue by Sudeepxl20** [yokoffing/filterlists#157]
When using yokoffing's Annoyance List the read more button still appears

Example

http://geeksforgeeks.org/transport-layer-responsibilities/

**Comment by yokoffing** [comment]
"Read more" links have to be made per site and can be complicated to implement.

There is a "similar reads" section at the bottom footer, but I don't see any "read more" sections breaking up the article.

**Comment by Sudeepxl20** [comment]
> When using yokoffing's Annoyance List the read more button still appears
> 
> Example
> 
> http://geeksforgeeks.org/transport-layer-r
![Screenshot_20240913_045208](https://github.com/user-attachments/assets/b07cfa82-193e-441a-bd15-21db35ad9090)
esponsibilities/

**Comment by yokoffing** [comment]
Ahh. I was looking at desktop, not mobile.

There's not much to be done about those. The "read more" I've tried to hide in the past are text-based.
