### ISSUE TITLE
lists question

### ISSUE THREAD

**Issue by LeeAdam258** [yokoffing/filterlists#159]
Hello, I want to ask if I can use the filter in combination with AdGuard as in the picture, basically my PC is quite old so I can't run a large amount of blocking files in combination with uBlock Origin
![Screenshot (159)](https://github.com/user-attachments/assets/befdc128-b930-4cf0-8cc7-d73aa15c46ca)

**Comment by yokoffing** [comment]
Yes, what you have is fine.
