### ISSUE TITLE
VK Video and RuTube embeds aren't blocked in the click2load filter

### ISSUE THREAD

**Issue by roastme** [yokoffing/filterlists#161]
VK Video: https://vk.com/video
RuTube: https://rutube.ru/

**Comment by yokoffing** [comment]
Are these used on third-party sites where the `click2load` rule would work? `*$3p,frame,redirect=click2load.html`

In other words, do you have any examples of these videos embedded on other sites?

**Comment by yokoffing** [comment]
Potential additions:
```adblock
||rutube.ru/video/$3p,frame,redirect=click2load.html
||vk.com/video/$3p,frame,redirect=click2load.html
```

**Comment by roastme** [comment]
<iframe src="https://vk.com/video_ext.php?oid=-22822305&id=456241864&hd=2" width="853" height="480" allow="autoplay; encrypted-media; fullscreen; picture-in-picture;" frameborder="0" allowfullscreen></iframe>
<iframe width="720" height="405" src="https://rutube.ru/play/embed/1438f27ce9a60cd28852324edb103644/" frameBorder="0" allow="clipboard-write; autoplay" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>

**Comment by yokoffing** [comment]
Are there any sites that you know that embed these videos?

These rules should work given what you provided, but I can't test until I have a third-party site that uses them.

```adblock
||vk.com/video_ext$3p,frame,redirect=click2load.html
||rutube.ru/play/embed/$3p,frame,redirect=click2load.html
```

**Comment by roastme** [comment]
VK video: https://yandex.ru/video/preview/17921360550277024695
rutube: https://yandex.ru/video/preview/14816315104277383459
it seems to work
