### ISSUE TITLE
Latest Privacy Essentials broke Google Captchas (specifically at login pages)

### ISSUE THREAD

**Issue by TheGITofTeo997** [yokoffing/filterlists#4]
### Prerequisites

- [X] I am not using any other content blockers alongside uBO (Privacy Badger, AdGuard, Ghostery, Adblock Plus, etc.)
- [X] I verified that this is not a [known filter issue](https://github.com/yokoffing/filterlists/issues)
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the uBO issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBO in the browser

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Specific URL(s) where the issue occurs

```bash
We can use this test website to spawn a reCAPTCHA demo, to get an example:

https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox.php
```

### Description

With the list enabled, the captcha box completely disappears, as it gets blocked.

### Logger Output

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +21 | \|\|google.com^$3p,domain=~cbsnews.com\|~flippity.net\|~translate.google.com\|~youtube-nocookie.com\|~youtube.com | -- | recaptcha-demo.appspot.com | 3 | frame | `https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LfW6wATAAAAAHLqO2pb8bDBahxlMxNdo9g947u9&co=aHR0cHM6Ly9yZWNhcHRjaGEtZGVtby5hcHBzcG90LmNvbTo0NDM.&hl=en&v=vP4jQKq0YJFzU6e21-BGy3GP&size=normal&cb=53kpa0mjtt2s` |
| +1 | \|\|google.com^$3p,domain=~cbsnews.com\|~flippity.net\|~translate.google.com\|~youtube-nocookie.com\|~youtube.com | -- | recaptcha-demo.appspot.com | 3 | frame | `https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LfW6wATAAAAAHLqO2pb8bDBahxlMxNdo9g947u9&co=aHR0cHM6Ly9yZWNhcHRjaGEtZGVtby5hcHBzcG90LmNvbTo0NDM.&hl=en&v=vP4jQKq0YJFzU6e21-BGy3GP&size=normal&cb=tosgztvz5nz0` |
| +1 |  |  | recaptcha-demo.appspot.com | 3 | image | `https://www.gstatic.com/recaptcha/admin/favicon.ico` |
| +1 |  |  | recaptcha-demo.appspot.com | 3 | script | `https://www.gstatic.com/recaptcha/releases/vP4jQKq0YJFzU6e21-BGy3GP/recaptcha__en.js` |
| +1 | googletagmanager_gtm.js | << | recaptcha-demo.appspot.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-123057962-1` |
| +1 | \|\|googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5 | -- | recaptcha-demo.appspot.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-123057962-1` |
| +1 | \|\|googletagmanager.com^ | -- | recaptcha-demo.appspot.com | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-123057962-1` |
| +1 | @@\|\|google.com/recaptcha/api.js | ++ | recaptcha-demo.appspot.com | 3 | script | `https://www.google.com/recaptcha/api.js?hl=en` |
| +0 |  |  | recaptcha-demo.appspot.com | 1 | doc | `https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox.php` |
</details>

### Expected behavior

The captcha boxes should appear

### Actual behavior

The captcha boxes get blocked at login pages

### uBlock Origin version

1.44.4

### Browser name and version

Firefox 105.3

### Operating System and version

Windows 11 22621

**Comment by mfarina122** [comment]
Same issue here, with same OS and browser version.

**Comment by yokoffing** [comment]
Fixed in https://github.com/yokoffing/filterlists/commit/5d3cdffa4e4bdcaed5917d431b91c55c532ea626
