### ISSUE TITLE
🛑 Enhanced website protection: don't block 'srht.site'

### ISSUE THREAD

**Issue by Sam-Oak** [yokoffing/filterlists#72]
### Prerequisites

- [X] I am not using any other content blockers alongside uBO (Privacy Badger, AdGuard, Ghostery, Adblock Plus, etc.)
- [x] I verified that this is not a [known filter issue](https://github.com/yokoffing/filterlists/issues)
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the uBO issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBO in the browser

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Specific URL(s) where the issue occurs

```bash
https://srht.site/
https://misterwww.srht.site/
```

### Description

`srht.site` hosts some sourcehut static pages.

this is the filter: https://github.com/yokoffing/filterlists/blob/1b35966db6f9d039d659005f6dba57e0e8c4b44b/enhanced_site_protection.txt#L14

### Logger Output

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 | \|\|site^$document,from=~anitube.site\|~blocklist.site\|~business.site\|~cdmstudy.site\|~dodi-repacks.site\|~first-party.site\|~fitgirl-repacks.site\|~fmoviesto.site\|~heimdall.site\|~metrolagu.site\|~nic.site\|~notube.site\|~secreto.site\|~thex.site\|~third-party.site\|~wuxiaworld.site | -- | srht.site | 1 | get | doc | `https://srht.site/` |
</details>

### Expected behavior

page loads

### Actual behavior

they are prevented from loading

### uBlock Origin version

1.47.2

### Browser name and version

Firefox 110.0.1

### Operating System and version

Windows 7

**Comment by yokoffing** [comment]
Thank you @Sam-Oak. If you find false positives for ETP list in the future, you can open a pull request instead with the correction. That will save you time from having to fill out the issue form.
