### ISSUE TITLE
annoyance_list breaks 23andme login

### ISSUE THREAD

**Issue by mahtd** [yokoffing/filterlists#75]
### Prerequisites

- [X] I am not using any other content blockers alongside uBO (Privacy Badger, AdGuard, Ghostery, Adblock Plus, etc.)
- [X] I verified that this is not a [known filter issue](https://github.com/yokoffing/filterlists/issues)
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the uBO issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBO in the browser

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Specific URL(s) where the issue occurs

```bash
https://auth.23andme.com/login/
```

### Description

Login form displays briefly and then crashes, leaving a mostly blank page behind (except for the header and footer)

<img width="492" alt="image" src="https://user-images.githubusercontent.com/6687627/226759744-e572770c-25fe-4a52-94ca-44e88c8a3101.png">

<img width="637" alt="image" src="https://user-images.githubusercontent.com/6687627/226759682-0039f6fa-5555-40c7-9e54-8825d771e706.png">

### Logger Output

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 |  |  | auth.23andme.com | 1 | get | image | `https://auth.23andme.com/app/auth/static/img/favicon.1a646afa62f5.ico` |
| +0 |  |  | auth.23andme.com | 1 | get | image | `https://auth.23andme.com/app/auth/static/img/apple-icon.76bc1ef60f8d.svg` |
| +0 |  |  | auth.23andme.com | 1 | get | image | `https://auth.23andme.com/app/auth/static/img/icons8-google.55de612562c7.svg` |
| +0 |  |  | auth.23andme.com | 1 | get | xhr | `https://auth.23andme.com/login/` |
| +0 | \|\|newrelic.com^ | -- | auth.23andme.com | 3 | get | script | `https://js-agent.newrelic.com/lazy-loader.540ab0d1-1227.min.js` |
| +0 | \|\|newrelic.com^ | -- | auth.23andme.com | 3 | get | script | `https://js-agent.newrelic.com/async-api.737e0ca6-1227.min.js` |
| +0 |  |  | auth.23andme.com | 1 | get | script | `https://auth.23andme.com/app/auth/static/js/lib/browser_update.min.25351ce6b5d9.js` |
| +0 |  |  | auth.23andme.com | 3 | get | font | `https://fonts.gstatic.com/s/atkinsonhyperlegible/v10/9Bt73C1KxNDXMspQ1lPyU89-1h6ONRlW45G8Wbc9dCWPRl-uFQ.woff2` |
| +0 |  |  | auth.23andme.com | 3 | get | font | `https://fonts.gstatic.com/s/atkinsonhyperlegible/v10/9Bt23C1KxNDXMspQ1lPyU89-1h6ONRlW45G04pIoWQeCbA.woff2` |
| +0 | `@@\|\|www.googletagmanager.com^` | ++ | auth.23andme.com | 3 | get | script | `https://www.googletagmanager.com/gtm.js?id=GTM-KWSG3N` |
| +0 | \|\|accounts.google.com/gsi/$script,3p | -- | auth.23andme.com | 3 | get | script | `https://accounts.google.com/gsi/client` |
| +0 |  |  | auth.23andme.com | 1 | get | image | `https://auth.23andme.com/app/auth/static/img/ttam_name_logo.d1dbc0855e13.svg` |
| +0 |  |  | auth.23andme.com | 1 | get | image | `https://auth.23andme.com/app/auth/static/img/logo_mob.1d0efb494245.svg` |
| +0 |  |  | auth.23andme.com | 1 | get | script | `https://auth.23andme.com/app/auth/static/js/index.a51cd67d3305.js` |
| +0 |  |  | auth.23andme.com | 3 | get | css | `https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400;700&display=swap` |
| +0 |  |  | auth.23andme.com | 1 | get | css | `https://auth.23andme.com/app/auth/static/css/browser_update.8072b9c6fb44.css` |
| +0 |  |  | auth.23andme.com | 1 | get | css | `https://auth.23andme.com/app/auth/static/css/main.c3323c336a96.css` |
| +0 | no-cosmetic-filtering: * true | -- | auth.23andme.com |  | get | dom | `https://auth.23andme.com/login/?next=https%3A//auth.23andme.com/authorize/%3Fredirect_uri%3Dhttps%253A%252F%252Fyou.23andme.com%252Fauth_callback%252F%26response_type%3Dcode%26client_id%3Dyou%26scope%3Dopenid%2Bancestry%2Bbasic%2Bhaplogroups%2Bnames%2Bphenotypes%253Aread%253Aall%2Bprofile_id%253Aall%26state%3D%257B%2522origin_uri%2522%253A%2B%2522%252Fp%252F3357644a7254cbda%252Ffamily%252Fnew-relatives%252F%253Fnum_new_relatives%253D33%2526route_key%253Dnewest_relatives%2526route_parameters%253D%25257B%252522num_new_relatives_string%252522%25253A%25252233%252522%25257D%2526target_profile_id%253D3357644a7254cbda%2526notify_source_id%253D2568770256%2526notify_source_channel%253Demail%2522%257D` |
| +0 |  |  | auth.23andme.com | 1 | get | doc | `https://auth.23andme.com/login/?next=https%3A//auth.23andme.com/authorize/%3Fredirect_uri%3Dhttps%253A%252F%252Fyou.23andme.com%252Fauth_callback%252F%26response_type%3Dcode%26client_id%3Dyou%26scope%3Dopenid%2Bancestry%2Bbasic%2Bhaplogroups%2Bnames%2Bphenotypes%253Aread%253Aall%2Bprofile_id%253Aall%26state%3D%257B%2522origin_uri%2522%253A%2B%2522%252Fp%252F3357644a7254cbda%252Ffamily%252Fnew-relatives%252F%253Fnum_new_relatives%253D33%2526route_key%253Dnewest_relatives%2526route_parameters%253D%25257B%252522num_new_relatives_string%252522%25253A%25252233%252522%25257D%2526target_profile_id%253D3357644a7254cbda%2526notify_source_id%253D2568770256%2526notify_source_channel%253Demail%2522%257D` |
</details>

### Expected behavior

Login form should display

### Actual behavior

Login form doesn't display

### uBlock Origin version

1.47.4

### Browser name and version

Arc 0.94.0 (Chromium 111.0.5563.64)

### Operating System and version

macOS 13.2.1 (22D68)

**Comment by Skillter** [comment]
The same filter breaks the login page on `https://x.com/`
