### ISSUE TITLE
Block Lists analysis 

### ISSUE THREAD

**Issue by kelvinkad** [yokoffing/filterlists#96]
Hi, I recently saw an analysis you made of hagezi lists. It was incredible.
I'd like to know your opinion about the main lists out there, if not all at least oisd, 1hosts and hagezi. Your opinion about what is the best and lightweight. I searched about what each one includes and I think hagezi is the more concise one. But I'd like to read from you what you think.

**Comment by yokoffing** [comment]
My recommendations are listed in this repo for ad blockers and in the NextDNS repo for DNS blocking.

You don't need another DNS blocklist if you're using Hagezi. If you're not using Hagezi,  you can [view an older version](https://github.com/yokoffing/NextDNS-Config/blob/e5518f6683aaa827f83ee002329d2215fd7e1a05/README.md#blocklists-1) of  the NextDNS Config guide and view https://github.com/yokoffing/NextDNS-Config/issues/19#issuecomment-1374911332.
