### ISSUE TITLE
Source of Optimized EasyList

### ISSUE THREAD

**Issue by dreadedhamish** [yokoffing/filterlists#97]
I'm wanting to know more about the optimized EasyList filter list.
The link is https://filters.adtidy.org/extension/ublock/filters/101_optimized.txt but going to adtidy redirects to the the Adguard homepage. 
Can you give me any more details about it? 
(among other things I'd like to find a HOSTS version of the file)

**Comment by yokoffing** [comment]
> adtidy redirects to the the Adguard homepage

Not sure why it’s redirecting for you, unless you’re using a redirect extension. The link works fine for me on Safari mobile and Firefox desktop.

> Can you give me any more details about it?

See https://github.com/yokoffing/filterlists#why-did-you-include-adguards-optimize-lists-but-not-adblock-plus-minified-lists and https://github.com/AdguardTeam/FiltersRegistry#filters-optimization. 

I doubt a HOSTS version exist.

I will add a bit more info when I’m back from traveling.

**Comment by dreadedhamish** [comment]
> > adtidy redirects to the the Adguard homepage
> 
> Not sure why it’s redirecting for you, unless you’re using a redirect extension. The link works fine for me on Safari mobile and Firefox desktop.
> 
> > Can you give me any more details about it?
> 
> See https://github.com/yokoffing/filterlists#why-did-you-include-adguards-optimize-lists-but-not-adblock-plus-minified-lists and https://github.com/AdguardTeam/FiltersRegistry#filters-optimization.
> 
> I doubt a HOSTS version exist.
> 
> I will add a bit more info when I’m back from traveling.

Thanks - that's very helpful.
The use case is a little niche - I'm wanting to add some light-weight filtering to my router. I'm using NextDNS, and only since I've been using it have I seen just how many DNS requests are being made to ad-servers etc... even with uBO installed on most browsers. So I was hoping to save some network traffic by blocking more requests at my router. The router is powerful but still resource constrained, and it isn't easy to quickly whitelist a site etc... so I was looking for a minimalist light-weight list that prioritises accuracy (low false-positives) to block some requests. 

So far I'm looking at this list:
https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist - a compilation of the most used advertising networks. 6500 rules.

**Comment by dreadedhamish** [comment]
Optimized Easylist - just taking the 3rdparty entries and converting to HOSTS would be about 9K lines.
I'm still learning about ABP format files, so maybe I'd need to extract more than just 3rdparty?
