### ISSUE TITLE
Update to uBlock Origin filter lists

### ISSUE THREAD

**Issue by waredrive** [yokoffing/filterlists#99]
It seems that uBlock has removed and added a few filter lists and some of the native lists mentioned in the configuration tutorial/guide are no longer present. Would it be possible to update the guide to implement the changes?

**Comment by yokoffing** [comment]
The repo just went through a major overhaul, so I'm assuming you mean the screenshot? I was waiting on the filterlist changes to fully roll out.

https://github.com/yokoffing/filterlists/commit/20f4c96660c40d244f26809e1c1fe291e40a1b34

**Comment by waredrive** [comment]
Thank you for a quick answer.  I have a question regarding the overhaulted version though. You state in the readme that "In addition to the default lists, you should also enable:". Could you please elaborate what is meant by "default lists". Does it mean the "Build-in" section for the dafault list or something more than that? Thanks.

**Comment by yokoffing** [comment]
All the lists that were enabled when you first installed ublock origin.
